version: '2.4'

services:
  laravel-php:
    extends:
      file: docker-compose.base.yml
      service: laravel-php
    depends_on:
      - laravel-db
    networks:
      - laravel

  laravel-nginx:
    extends:
      file: docker-compose.base.yml
      service: laravel-nginx
    depends_on:
      - laravel-db
    ports:
      - ${APP_PORT}:80
    networks:
      - laravel

  laravel-db:
    extends:
      file: docker-compose.base.yml
      service: laravel-db
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOTPASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - laravel

networks:
  laravel:
    name: laravel

volumes:
  data_laravel:
